# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

""""  QT designer """
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Values = QtWidgets.QTableWidget(self.centralwidget)
        self.Values.setGeometry(QtCore.QRect(140, 150, 381, 91))
        self.Values.setObjectName("Values")
        self.Values.setColumnCount(3)
        self.Values.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.Values.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Values.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Values.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Values.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Values.setHorizontalHeaderItem(2, item)
        self.com = QtWidgets.QComboBox(self.centralwidget)
        self.com.setGeometry(QtCore.QRect(20, 130, 69, 22))
        self.com.setObjectName("com")
        self.com.addItem("")
        self.com.addItem("")
        self.com.addItem("")
        self.com.addItem("")
        self.com.addItem("")
        self.com.addItem("")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(400, 370, 75, 23))
        self.stop.setObjectName("stop")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(270, 370, 75, 23))
        self.reset.setObjectName("reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuchuro = QtWidgets.QMenu(self.menubar)
        self.menuchuro.setObjectName("menuchuro")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuchuro.menuAction())
        self.reset.clicked.connect(self.resetAction)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def resetAction(self):
        print("reset")
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.Values.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Values.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.Values.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor"))
        item = self.Values.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        item = self.Values.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        
        
        
        
        self.com.setItemText(0, _translate("MainWindow", "COM1"))
        self.com.setItemText(1, _translate("MainWindow", "COM2"))
        self.com.setItemText(2, _translate("MainWindow", "COM3"))
        self.com.setItemText(3, _translate("MainWindow", "COM4"))
        self.com.setItemText(4, _translate("MainWindow", "COM5"))
        self.com.setItemText(5, _translate("MainWindow", "COM6"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.menuchuro.setTitle(_translate("MainWindow", "churo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
